simplified unmounting and luks scripts

diff --git a/uitools/rluksclose b/uitools/rluksclose
--- a/uitools/rluksclose
+++ b/uitools/rluksclose
@@ -6,7 +6,14 @@ mappedluks="$(lsblk -rpo "name,type,size,fstype,mountpoint" | awk '$2=="crypt"&&
 closeluks() { \
 	chosen="$(echo "$mappedluks" | rofi -dmenu -i -p "Close which LUKS mapping?" | awk '{print $1}')";
 	if [ -n "$chosen" ]; then
-		sudo -A cryptsetup luksClose "$chosen" && notify-send " LUKS closing" "$chosen closed." && exit 0;
+		sudo -A cryptsetup luksClose "$chosen";
+		exit_code=$?;
+		if [ "$exit_code" -eq 0 ]; then
+			notify-send " LUKS closing" "$chosen closed.";
+		else
+			notify-send " LUKS error ($exit_code)" "couldn't close $chosen."
+			exit "$exit_code";
+		fi;
 	fi;
 }
 
diff --git a/uitools/rluksopen b/uitools/rluksopen
--- a/uitools/rluksopen
+++ b/uitools/rluksopen
@@ -9,9 +9,14 @@ openluks() { \
 	chosen="$(echo "$hotluks" | rofi -dmenu -i -p "Open which LUKS drive?" | awk '{print $1}')";
 	if [ -n "$chosen" ]; then
 		mapped=$(echo "$chosen" | awk -F '/' '{print $NF 1}');
-		sudo -A cryptsetup luksOpen "$chosen" "$mapped" && notify-send " LUKS opening" "$chosen opened." && exit 0;
-	else
-		exit 2;
+		sudo -A cryptsetup luksOpen "$chosen" "$mapped";
+		exit_code=$?;
+		if [ "$exit_code" -eq 0 ]; then
+			notify-send " LUKS opening" "$chosen opened.";
+		else
+			notify-send " LUKS error ($exit_code)" "couldn't open $chosen."
+			exit "$exit_code";
+		fi;
 	fi;
 }
 
